### ISSUE TITLE
YAML format to replace verbose JSON templates

### ISSUE THREAD

**Issue by yongfei25** [SomeoneWeird/cirrus#20]
Just thinking if we can implement some YAML to JSON template converter. 
YAML format is simpler and supports comments in the template.

``` yml
description: Create postgres database
parameters:
 - RDSInstanceClass:
     - description: DB instance type
       type: string
resources:
  # And you can drop comments here
 - DatastoreDBSubnetGroup:
    - Type: AWS::RDS::DBInstance
       DeletionPolicy: Retain
       Properties:
        - DBInstanceClass: <<RDSInstanceClass>>

```
