### ISSUE TITLE
Ability to generate the current date (in UTC) in parameter files

### ISSUE THREAD

**Issue by joffotron** [SomeoneWeird/cirrus#31]
e.g. for Cfn template:

```yaml
Resources:
  BKAgentSleepAtNight:
    Type: AWS::AutoScaling::ScheduledAction
    Condition: UseAutoscaling
    Properties:
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 2
      StartTime: "2017-07-28T09:00:00Z"
      Recurrence: "0 9 * * MON-FRI"
```

If that date is in the past then Cfn will tell you to go away. 

We could have `{ "MyParam": "<<currentDate: yyyy-mm-dd>>"}` or something similar.

Leaving this mostly as a note to myself ;)
